from pathlib import Path
root=Path('/mnt/data/gficonfix')
common_css='''
:root{--bg:#0f0c06;--card:#1c1710;--card2:#272016;--border:#4a3c24;--gold:#e8c547;--gold2:#ffc52e;--text:#f5eedc;--muted:#a79778;--green:#21c46b;--red:#e4574f}
*{box-sizing:border-box;-webkit-tap-highlight-color:transparent}html,body{margin:0;min-height:100%;background:var(--bg);color:var(--text);font-family:DM Sans,system-ui,sans-serif}body{background:radial-gradient(800px 360px at 50% -80px,rgba(232,197,71,.10),transparent 70%),var(--bg)}
.wrap{width:min(100%,720px);margin:auto;padding:22px 18px 48px}.top{display:flex;align-items:center;gap:18px;margin:18px 0 28px}.back{width:46px;height:46px;display:grid;place-items:center;border:0;background:transparent;color:#f5eedc;text-decoration:none;font-size:42px;line-height:1}.top h1{margin:0;font:700 2rem/1.1 'Playfair Display',serif;color:#f5eedc}
.hero-card,.card{background:linear-gradient(145deg,rgba(40,33,22,.92),rgba(25,20,13,.96));border:1px solid rgba(232,197,71,.34);border-radius:25px;box-shadow:0 22px 70px rgba(0,0,0,.28);padding:28px 26px;margin-bottom:18px}.hero-card{position:relative;overflow:hidden}.hero-card:after{content:"";position:absolute;width:220px;height:220px;right:-100px;top:-100px;background:radial-gradient(circle,rgba(232,197,71,.15),transparent 68%);pointer-events:none}
.iconbox{width:74px;height:74px;border-radius:22px;display:grid;place-items:center;border:1px solid rgba(232,197,71,.42);background:rgba(232,197,71,.07);margin-bottom:20px}.iconbox svg{width:39px;height:39px;fill:none;stroke:var(--gold);stroke-width:1.7;stroke-linecap:round;stroke-linejoin:round}.eyebrow{color:var(--muted);font-size:.84rem;margin-bottom:7px}.title{font:700 1.65rem/1.15 'Playfair Display',serif;margin:0 0 10px}.desc{color:var(--muted);line-height:1.65;margin:0}.btn{width:100%;min-height:54px;border-radius:15px;border:1px solid var(--gold);background:linear-gradient(180deg,#ffc936,#e9ad1f);color:#171207;font-weight:800;font-size:1rem;display:flex;align-items:center;justify-content:center;gap:10px;text-decoration:none;cursor:pointer;margin-top:18px}.btn.outline{background:transparent;color:var(--gold)}
.section-title{font:700 1.65rem/1.15 'Playfair Display',serif;margin:30px 0 16px}.grid{display:grid;gap:14px}.two{grid-template-columns:repeat(2,minmax(0,1fr))}.row{display:flex;justify-content:space-between;gap:14px;align-items:center}.label{color:var(--muted);font-size:.9rem}.value{font-weight:800;font-size:1.15rem}.gold{color:var(--gold)}
.plan{padding:28px 26px;border-radius:24px;background:linear-gradient(145deg,#252016,#19140d);border:1px solid rgba(232,197,71,.32);margin-bottom:18px}.plan-head{display:flex;align-items:center;gap:12px;margin-bottom:18px}.plan-star{font-size:30px;color:#ffc52e}.medal{font-size:25px}.plan-name{font:700 1.55rem 'Playfair Display',serif}.plan-desc{color:var(--muted);font-size:1rem;line-height:1.45;margin-bottom:18px}.plan-meta{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-bottom:18px}.plan-meta .value{font:700 1.55rem 'Playfair Display',serif;color:var(--text);margin-top:4px}.plan .btn{margin-top:10px}.plan .btn.outline{border-width:2px}
.link-card{display:flex;align-items:center;gap:15px;text-decoration:none;color:var(--text);background:linear-gradient(145deg,#252016,#19140d);border:1px solid rgba(232,197,71,.28);border-radius:20px;padding:18px;margin-bottom:12px}.link-icon{width:52px;height:52px;border-radius:16px;display:grid;place-items:center;background:rgba(232,197,71,.08);border:1px solid rgba(232,197,71,.28);color:var(--gold);font-size:25px}.link-title{font-weight:800}.link-sub{display:block;color:var(--muted);font-size:.82rem;margin-top:4px}
.info{background:#30291f;border-radius:17px;padding:17px 18px;margin:11px 0}.info .label{display:block;margin-bottom:5px}.info .value{font-size:1.05rem;word-break:break-word}.code{font:800 1.7rem 'Playfair Display',serif;letter-spacing:2px;color:var(--gold);margin:8px 0}
.small-note{color:var(--muted);font-size:.82rem;line-height:1.55;margin-top:12px}.empty{padding:26px;text-align:center;color:var(--muted)}
@media(max-width:460px){.wrap{padding-left:16px;padding-right:16px}.top h1{font-size:1.8rem}.hero-card,.card,.plan{padding:24px 22px}.two{grid-template-columns:1fr 1fr}.plan-meta .value{font-size:1.35rem}}
'''

def page(title, icon, body):
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><meta name="theme-color" content="#0f0c06"><title>Gold Fortune — {title}</title><link rel="icon" href="icon-2.png"><link rel="manifest" href="manifest.json"><link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@500;600;700&family=DM+Sans:wght@300;400;500;600;700;800&display=swap" rel="stylesheet"><style>{common_css}</style></head><body><main class="wrap"><div class="top"><a class="back" href="dashboard.html" aria-label="Back">‹</a><h1>{title}</h1></div>{body}</main><script src="app.js"></script><script>if(!getLoggedUser()){{location.replace('login.html');}}</script></body></html>'''

product_body='''<section class="hero-card"><div class="iconbox"><svg viewBox="0 0 24 24"><path d="M6 8h12l1 13H5L6 8Z"/><path d="M9 8V6a3 3 0 0 1 6 0v2"/><path d="M9 12c0 2 6 2 6 0"/></svg></div><div class="eyebrow">GOLD FORTUNE</div><h2 class="title">Products</h2><p class="desc">Choose an available plan and review its investment and return details.</p></section><div id="plans"><div class="empty">Loading products…</div></div><a class="btn outline" href="dashboard.html">Return to Dashboard</a><script>async function loadProducts(){try{const d=await fetchBin();const list=Array.isArray(d.products)?d.products:[];const medals=['🥉','🥈','🥇','💎','👑'];document.getElementById('plans').innerHTML=list.length?list.map((p,i)=>`<article class="plan"><div class="plan-head"><span class="plan-star">☆</span><span class="medal">${medals[i%medals.length]}</span><span class="plan-name">${p.name||'Plan'}</span></div><div class="plan-desc">${p.desc||''}</div><div class="plan-meta"><div><div class="label">Investment</div><div class="value">₦${Number(p.price||0).toLocaleString()}</div></div><div><div class="label">Profit</div><div class="value">₦${Number(p.profit||0).toLocaleString()}</div></div></div><button class="btn" onclick="location.href='dashboard.html'">▢ &nbsp; Buy Product</button><button class="btn outline" onclick="location.href='dashboard.html'">♧ &nbsp; Verify &amp; Claim Product</button></article>`).join(''):'<div class="empty">No products available</div>';}catch(e){document.getElementById('plans').innerHTML='<div class="empty">Unable to load products.</div>';}}loadProducts();</script>'''

support_body='''<section class="hero-card"><div class="iconbox"><svg viewBox="0 0 24 24"><path d="M4 14v-2a8 8 0 0 1 16 0v2"/><path d="M4 14v3a2 2 0 0 0 2 2h1v-7H6a2 2 0 0 0-2 2Z"/><path d="M20 14v3a2 2 0 0 1-2 2h-1v-7h1a2 2 0 0 1 2 2Z"/></svg></div><div class="eyebrow">GOLD FORTUNE</div><h2 class="title">Support</h2><p class="desc">Reach the available support channels whenever you need assistance.</p></section><section class="card"><div id="supportList"><div class="empty">Loading support channels…</div></div></section><a class="btn outline" href="dashboard.html">Return to Dashboard</a><script>async function loadSupport(){try{const d=await fetchBin();const s=d.settings||{};const links=[['💬','WhatsApp Support','Chat with support',s.whatsapp],['✈','Telegram','Message support',s.telegram],['◉','Telegram Channel','News and updates',s.telegramChannel]].filter(x=>x[3]);document.getElementById('supportList').innerHTML=links.length?links.map(x=>`<a class="link-card" href="${x[3]}" target="_blank" rel="noopener"><span class="link-icon">${x[0]}</span><span><span class="link-title">${x[1]}</span><span class="link-sub">${x[2]}</span></span></a>`).join(''):'<div class="empty">Support channels are currently unavailable.</div>';}catch(e){}}loadSupport();</script>'''

platform_body='''<section class="hero-card"><div class="iconbox"><svg viewBox="0 0 24 24"><rect x="4" y="4" width="6" height="6" rx="1"/><rect x="14" y="4" width="6" height="6" rx="1"/><rect x="4" y="14" width="6" height="6" rx="1"/><rect x="14" y="14" width="6" height="6" rx="1"/></svg></div><div class="eyebrow">GOLD FORTUNE</div><h2 class="title">Platform</h2><p class="desc">Your Gold Fortune platform information and current payment details.</p></section><section class="card"><h2 class="section-title" style="margin-top:0">Platform Details</h2><div class="info"><span class="label">Payment Bank</span><span class="value" id="bank">—</span></div><div class="info"><span class="label">Account Name</span><span class="value" id="name">—</span></div><div class="info"><span class="label">Account Number</span><span class="value" id="acct">—</span></div></section><a class="btn" href="dashboard.html">Make a Deposit</a><a class="btn outline" href="dashboard.html">Return to Dashboard</a><script>fetchBin().then(d=>{const s=d.settings||{};document.getElementById('bank').textContent=s.bankName||'—';document.getElementById('name').textContent=s.accountName||'—';document.getElementById('acct').textContent=s.bankAccount||'—';}).catch(()=>{});</script>'''

invite_body='''<section class="hero-card"><div class="iconbox"><svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"/><path d="M3 20v-2a6 6 0 0 1 12 0v2"/><path d="M16 5.5a3 3 0 0 1 0 5.8"/><path d="M18 14a5 5 0 0 1 3 4.5V20"/></svg></div><div class="eyebrow">GOLD FORTUNE</div><h2 class="title">Invite &amp; Earn</h2><p class="desc">Share your referral code and track your referral rewards.</p></section><section class="card"><div class="label">Your referral code</div><div class="code" id="code">—</div><button class="btn" onclick="copyCode()">Copy Code</button></section><div class="grid two"><div class="card" style="text-align:center"><div class="value gold" id="refs">0</div><div class="label">Total Invites</div></div><div class="card" style="text-align:center"><div class="value gold" id="earn">₦0</div><div class="label">Invite Earnings</div></div></div><section class="card"><p class="desc">Use your referral link to invite friends and build your network.</p></section><a class="btn outline" href="dashboard.html">Return to Dashboard</a><script>const u=getLoggedUser()||{};document.getElementById('code').textContent=u.referralCode||u.id||'—';document.getElementById('earn').textContent='₦'+Number(u.inviteEarnings||0).toLocaleString();fetchBin().then(d=>{const me=(d.users||[]).find(x=>x.email===u.email);if(me){document.getElementById('refs').textContent=Number(me.referrals||0);document.getElementById('earn').textContent='₦'+Number(me.inviteEarnings||0).toLocaleString();}}).catch(()=>{});function copyCode(){navigator.clipboard.writeText(document.getElementById('code').textContent).then(()=>alert('Referral code copied')).catch(()=>{});}</script>'''

profile_body='''<section class="hero-card"><div class="iconbox"><svg viewBox="0 0 24 24"><circle cx="12" cy="7" r="3.5"/><path d="M5 21v-2.5a7 7 0 0 1 14 0V21"/></svg></div><div class="eyebrow">GOLD FORTUNE</div><h2 class="title">Profile</h2><p class="desc">View your account details and saved withdrawal bank information.</p></section><section class="card"><div class="info"><span class="label">Full Name</span><span class="value" id="full">—</span></div><div class="info"><span class="label">Email</span><span class="value" id="email">—</span></div><div class="info"><span class="label">Joined</span><span class="value" id="joined">—</span></div><div class="info"><span class="label">Status</span><span class="value gold" id="status">Active</span></div><div class="info"><span class="label">Referral Code</span><span class="value" id="ref">—</span></div></section><section class="card"><h2 class="section-title" style="margin-top:0">Bank Details</h2><div class="info"><span class="label">Your Bank</span><span class="value" id="bank">Not set</span></div><div class="info"><span class="label">Account Number</span><span class="value" id="acct">Not set</span></div><p class="small-note">Update your withdrawal bank from the Add Bank option on the dashboard.</p></section><button class="btn outline" onclick="clearLoggedUser();location.replace('login.html')">Logout</button><a class="btn outline" href="dashboard.html">Return to Dashboard</a><script>const u=getLoggedUser()||{};document.getElementById('full').textContent=u.fullName||'—';document.getElementById('email').textContent=u.email||'—';document.getElementById('joined').textContent=u.joined?new Date(u.joined).toLocaleDateString():'—';document.getElementById('status').textContent=u.status||'Active';document.getElementById('ref').textContent=u.referralCode||u.id||'—';document.getElementById('bank').textContent=u.bankName||'Not set';document.getElementById('acct').textContent=u.bankAccount||'Not set';</script>'''

for fn,title,icon,body in [('product.html','Products','bag',product_body),('support.html','Support','headset',support_body),('platform.html','Platform','grid',platform_body),('invite.html','Invite','people',invite_body),('profile.html','Profile','person',profile_body)]:
    (root/fn).write_text(page(title,icon,body),encoding='utf-8')

# make dashboard nav icons and spacing match the video more closely
p=root/'dashboard.html'; s=p.read_text(encoding='utf-8')
s=s.replace('.nav-item{font-size:.78rem;text-decoration:none}.nav-icon{width:62px;height:62px;border-radius:18px;', '.nav-item{font-size:.78rem;text-decoration:none}.nav-icon{width:62px;height:62px;border-radius:18px;')
# Existing styling already had 62px from prior update. Add stronger video-like label/spacing if not present.
s=s.replace('.quick-nav{display:flex;justify-content:space-between;gap:6px;margin-bottom:28px}', '.quick-nav{display:flex;justify-content:space-between;gap:7px;margin-bottom:30px;padding:0 2px}')
s=s.replace('.nav-item{flex:1;display:flex;flex-direction:column;align-items:center;gap:8px;', '.nav-item{flex:1;display:flex;flex-direction:column;align-items:center;gap:9px;')
s=s.replace('font-size:.78rem;text-decoration:none', 'font-size:.78rem;text-decoration:none;font-weight:500')
p.write_text(s,encoding='utf-8')
